
function createfigure1(X1, Y1, Y2, Y3,handles)
%CREATEFIGURE(X1,Y1,Y2,Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 31-Mar-2017 18:49:05

% Create figure
%figure1 = figure(2);

% Create sub-plot
%subplot1 = subplot(1,3,3,'Parent',figure1);
axes(handles.axes3);
%box(subplot1,'on');
%hold(subplot1,'all');
hold on
% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 1 0]);

% Create x-label
xlabel('Round','FontWeight','bold','FontSize',11,'FontName','Cambria');

% Create y-label
ylabel('sum d"energie','FontWeight','bold','FontSize',11,...
    'FontName','Cambria');

% Create title
title('Sum d"energie des noeuds par round','FontWeight','bold','FontSize',12,...
    'FontName','Cambria');
hold off
axes(handles.axes4);
% Create sub-plot
%subplot2 = subplot(1,3,1,'Parent',figure1);
%box(subplot2,'on');
%hold(subplot2,'all');
hold on
% Create plot
plot(X1,Y2,'LineWidth',2);

% Create x-label
xlabel('Round','FontWeight','bold','FontSize',11,'FontName','Cambria');

% Create y-label
ylabel('# of paquets envoyés à la SB','FontWeight','bold','FontSize',11,...
    'FontName','Cambria');

% Create title
title('# de paquets envoyés à la SB par round','FontWeight','bold',...
    'FontSize',12,...
    'FontName','Cambria');
hold off
axes(handles.axes5);
% Create sub-plot
%subplot3 = subplot(1,3,2,'Parent',figure1);
%box(subplot3,'on');
%hold(subplot3,'all');
hold on
% Create plot
plot(X1,Y3,'LineWidth',2,'Color',[1 0 0]);

% Create x-label
xlabel('Round','FontWeight','bold','FontSize',11,'FontName','Cambria');

% Create y-label
ylabel('# de noeuds morts','FontWeight','bold','FontSize',11,...
    'FontName','Cambria');

% Create title
title('nombre de noeuds morts par round','FontWeight','bold','FontSize',12,...
    'FontName','Cambria');

hold off